### ISSUE TITLE
Using an array as numPlayers.

### ISSUE THREAD

**Issue by TheRedSock** [clux/group#1]
Not an issue but a feature that I would find extremely useful, if I could input an array (which we assume is sorted to be seeded), and the now every group would then contain the correct array indexes. This way I could import a text file of players from a seeding chart, and then pop that array into the algorithm to instantly create pools with the correct names.

**Comment by clux** [comment]
Yeah, I would find that feature useful as well. There's already a similar helper in [roundrobin](https://github.com/clux/roundrobin), so see no reason why we shouldn't have a similar one for this.

**Comment by TheRedSock** [comment]
Ah, that is very nice. How would I go about using that if I have an array of names (say 32 names), and I want to  sort these out in 8 seeded groups with 4 players each? Seems like the roundrobin application doesn't really account for seeding and only lists matches that has to be played.

**Comment by clux** [comment]
Yeah, roundrobin doesn't benefit from having the seeding information as everyone just plays everyone anyway.

Ideally, would want `group(ary, numGroups)` to partition `ary`. Do you want to implement this?

**Comment by TheRedSock** [comment]
Yeah, that's what I would like to do, be able to insert an array as a parameter and have the application print out the names instead of just the numbers. I'm not a very experienced programmer, so I'm not sure quite how much reworking would be needed to do that :/

**Comment by clux** [comment]
Cool. Yeah, no worries. I can probably implement that in a few minutes later today.

**Comment by clux** [comment]
Changed it slightly from what I said above, but `group@0.3.0` has a `fromArray` function in https://github.com/clux/group/commit/c7ab965125a86711ac933cf20636df5bc90db085

**Comment by TheRedSock** [comment]
Ah cool man, thanks so much!
